spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_UPPER=false;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true